platform :ios, '9.0'

target 'FMNetworkingExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'FMNetworking', :path => './../'

end
